name: retainly

services:
  migrate:
    image: ${MIGRATE_IMAGE:?MIGRATE_IMAGE chua duoc dat}
    container_name: retainly-${STACK}-migrate
    environment:
      TZ: Asia/Ho_Chi_Minh
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres-sit:5432/${DB_NAME}?schema=public&options=-c%20timezone%3DUTC
    networks: [db]
    restart: 'no'
    security_opt:
      - no-new-privileges:true

  api:
    image: ${API_IMAGE:?API_IMAGE chua duoc dat}
    container_name: retainly-${STACK}-api
    restart: unless-stopped
    environment:
      TZ: Asia/Ho_Chi_Minh
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres-sit:5432/${DB_NAME}?schema=public&options=-c%20timezone%3DUTC
      APP_ORIGIN: ${APP_ORIGIN:?APP_ORIGIN chua duoc dat}
      OIDC_ISSUER: ${OIDC_ISSUER:?OIDC_ISSUER chua duoc dat}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:?OIDC_CLIENT_ID chua duoc dat}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:?OIDC_CLIENT_SECRET chua duoc dat}
      SESSION_COOKIE_SECRET: ${SESSION_COOKIE_SECRET:?SESSION_COOKIE_SECRET chua duoc dat}
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks: [edge, db]
    security_opt:
      - no-new-privileges:true

  web:
    image: ${WEB_IMAGE:?WEB_IMAGE chua duoc dat}
    container_name: retainly-${STACK}-web
    restart: unless-stopped
    environment:
      TZ: Asia/Ho_Chi_Minh
    networks: [edge]
    security_opt:
      - no-new-privileges:true

networks:
  edge:
    name: edge
    external: true
  db:
    name: db-sit
    external: true
